package antidote;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import antidote.ObjectUser;
import antidote.ObjectProduct;
import antidote.ObjectCategory;
import antidote.ObjectCountry;
import antidote.ObjectComment;
import antidote.ObjectOption;
import antidote.ObjectProductOption;
import antidote.ObjectGroupProduct;
import antidote.ObjectGroupTimer;
import antidote.ObjectCart;
import antidote.ObjectOrderDelivery;
import antidote.ObjectBanner;
import antidote.ObjectOrderHistory;
import antidote.ObjectCoupon;
import antidote.ObjectFaq;
import antidote.ObjectFaqComment;
import antidote.ObjectFaqV2;

import antidote.ObjectUserDao;
import antidote.ObjectProductDao;
import antidote.ObjectCategoryDao;
import antidote.ObjectCountryDao;
import antidote.ObjectCommentDao;
import antidote.ObjectOptionDao;
import antidote.ObjectProductOptionDao;
import antidote.ObjectGroupProductDao;
import antidote.ObjectGroupTimerDao;
import antidote.ObjectCartDao;
import antidote.ObjectOrderDeliveryDao;
import antidote.ObjectBannerDao;
import antidote.ObjectOrderHistoryDao;
import antidote.ObjectCouponDao;
import antidote.ObjectFaqDao;
import antidote.ObjectFaqCommentDao;
import antidote.ObjectFaqV2Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig objectUserDaoConfig;
    private final DaoConfig objectProductDaoConfig;
    private final DaoConfig objectCategoryDaoConfig;
    private final DaoConfig objectCountryDaoConfig;
    private final DaoConfig objectCommentDaoConfig;
    private final DaoConfig objectOptionDaoConfig;
    private final DaoConfig objectProductOptionDaoConfig;
    private final DaoConfig objectGroupProductDaoConfig;
    private final DaoConfig objectGroupTimerDaoConfig;
    private final DaoConfig objectCartDaoConfig;
    private final DaoConfig objectOrderDeliveryDaoConfig;
    private final DaoConfig objectBannerDaoConfig;
    private final DaoConfig objectOrderHistoryDaoConfig;
    private final DaoConfig objectCouponDaoConfig;
    private final DaoConfig objectFaqDaoConfig;
    private final DaoConfig objectFaqCommentDaoConfig;
    private final DaoConfig objectFaqV2DaoConfig;

    private final ObjectUserDao objectUserDao;
    private final ObjectProductDao objectProductDao;
    private final ObjectCategoryDao objectCategoryDao;
    private final ObjectCountryDao objectCountryDao;
    private final ObjectCommentDao objectCommentDao;
    private final ObjectOptionDao objectOptionDao;
    private final ObjectProductOptionDao objectProductOptionDao;
    private final ObjectGroupProductDao objectGroupProductDao;
    private final ObjectGroupTimerDao objectGroupTimerDao;
    private final ObjectCartDao objectCartDao;
    private final ObjectOrderDeliveryDao objectOrderDeliveryDao;
    private final ObjectBannerDao objectBannerDao;
    private final ObjectOrderHistoryDao objectOrderHistoryDao;
    private final ObjectCouponDao objectCouponDao;
    private final ObjectFaqDao objectFaqDao;
    private final ObjectFaqCommentDao objectFaqCommentDao;
    private final ObjectFaqV2Dao objectFaqV2Dao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        objectUserDaoConfig = daoConfigMap.get(ObjectUserDao.class).clone();
        objectUserDaoConfig.initIdentityScope(type);

        objectProductDaoConfig = daoConfigMap.get(ObjectProductDao.class).clone();
        objectProductDaoConfig.initIdentityScope(type);

        objectCategoryDaoConfig = daoConfigMap.get(ObjectCategoryDao.class).clone();
        objectCategoryDaoConfig.initIdentityScope(type);

        objectCountryDaoConfig = daoConfigMap.get(ObjectCountryDao.class).clone();
        objectCountryDaoConfig.initIdentityScope(type);

        objectCommentDaoConfig = daoConfigMap.get(ObjectCommentDao.class).clone();
        objectCommentDaoConfig.initIdentityScope(type);

        objectOptionDaoConfig = daoConfigMap.get(ObjectOptionDao.class).clone();
        objectOptionDaoConfig.initIdentityScope(type);

        objectProductOptionDaoConfig = daoConfigMap.get(ObjectProductOptionDao.class).clone();
        objectProductOptionDaoConfig.initIdentityScope(type);

        objectGroupProductDaoConfig = daoConfigMap.get(ObjectGroupProductDao.class).clone();
        objectGroupProductDaoConfig.initIdentityScope(type);

        objectGroupTimerDaoConfig = daoConfigMap.get(ObjectGroupTimerDao.class).clone();
        objectGroupTimerDaoConfig.initIdentityScope(type);

        objectCartDaoConfig = daoConfigMap.get(ObjectCartDao.class).clone();
        objectCartDaoConfig.initIdentityScope(type);

        objectOrderDeliveryDaoConfig = daoConfigMap.get(ObjectOrderDeliveryDao.class).clone();
        objectOrderDeliveryDaoConfig.initIdentityScope(type);

        objectBannerDaoConfig = daoConfigMap.get(ObjectBannerDao.class).clone();
        objectBannerDaoConfig.initIdentityScope(type);

        objectOrderHistoryDaoConfig = daoConfigMap.get(ObjectOrderHistoryDao.class).clone();
        objectOrderHistoryDaoConfig.initIdentityScope(type);

        objectCouponDaoConfig = daoConfigMap.get(ObjectCouponDao.class).clone();
        objectCouponDaoConfig.initIdentityScope(type);

        objectFaqDaoConfig = daoConfigMap.get(ObjectFaqDao.class).clone();
        objectFaqDaoConfig.initIdentityScope(type);

        objectFaqCommentDaoConfig = daoConfigMap.get(ObjectFaqCommentDao.class).clone();
        objectFaqCommentDaoConfig.initIdentityScope(type);

        objectFaqV2DaoConfig = daoConfigMap.get(ObjectFaqV2Dao.class).clone();
        objectFaqV2DaoConfig.initIdentityScope(type);

        objectUserDao = new ObjectUserDao(objectUserDaoConfig, this);
        objectProductDao = new ObjectProductDao(objectProductDaoConfig, this);
        objectCategoryDao = new ObjectCategoryDao(objectCategoryDaoConfig, this);
        objectCountryDao = new ObjectCountryDao(objectCountryDaoConfig, this);
        objectCommentDao = new ObjectCommentDao(objectCommentDaoConfig, this);
        objectOptionDao = new ObjectOptionDao(objectOptionDaoConfig, this);
        objectProductOptionDao = new ObjectProductOptionDao(objectProductOptionDaoConfig, this);
        objectGroupProductDao = new ObjectGroupProductDao(objectGroupProductDaoConfig, this);
        objectGroupTimerDao = new ObjectGroupTimerDao(objectGroupTimerDaoConfig, this);
        objectCartDao = new ObjectCartDao(objectCartDaoConfig, this);
        objectOrderDeliveryDao = new ObjectOrderDeliveryDao(objectOrderDeliveryDaoConfig, this);
        objectBannerDao = new ObjectBannerDao(objectBannerDaoConfig, this);
        objectOrderHistoryDao = new ObjectOrderHistoryDao(objectOrderHistoryDaoConfig, this);
        objectCouponDao = new ObjectCouponDao(objectCouponDaoConfig, this);
        objectFaqDao = new ObjectFaqDao(objectFaqDaoConfig, this);
        objectFaqCommentDao = new ObjectFaqCommentDao(objectFaqCommentDaoConfig, this);
        objectFaqV2Dao = new ObjectFaqV2Dao(objectFaqV2DaoConfig, this);

        registerDao(ObjectUser.class, objectUserDao);
        registerDao(ObjectProduct.class, objectProductDao);
        registerDao(ObjectCategory.class, objectCategoryDao);
        registerDao(ObjectCountry.class, objectCountryDao);
        registerDao(ObjectComment.class, objectCommentDao);
        registerDao(ObjectOption.class, objectOptionDao);
        registerDao(ObjectProductOption.class, objectProductOptionDao);
        registerDao(ObjectGroupProduct.class, objectGroupProductDao);
        registerDao(ObjectGroupTimer.class, objectGroupTimerDao);
        registerDao(ObjectCart.class, objectCartDao);
        registerDao(ObjectOrderDelivery.class, objectOrderDeliveryDao);
        registerDao(ObjectBanner.class, objectBannerDao);
        registerDao(ObjectOrderHistory.class, objectOrderHistoryDao);
        registerDao(ObjectCoupon.class, objectCouponDao);
        registerDao(ObjectFaq.class, objectFaqDao);
        registerDao(ObjectFaqComment.class, objectFaqCommentDao);
        registerDao(ObjectFaqV2.class, objectFaqV2Dao);
    }
    
    public void clear() {
        objectUserDaoConfig.getIdentityScope().clear();
        objectProductDaoConfig.getIdentityScope().clear();
        objectCategoryDaoConfig.getIdentityScope().clear();
        objectCountryDaoConfig.getIdentityScope().clear();
        objectCommentDaoConfig.getIdentityScope().clear();
        objectOptionDaoConfig.getIdentityScope().clear();
        objectProductOptionDaoConfig.getIdentityScope().clear();
        objectGroupProductDaoConfig.getIdentityScope().clear();
        objectGroupTimerDaoConfig.getIdentityScope().clear();
        objectCartDaoConfig.getIdentityScope().clear();
        objectOrderDeliveryDaoConfig.getIdentityScope().clear();
        objectBannerDaoConfig.getIdentityScope().clear();
        objectOrderHistoryDaoConfig.getIdentityScope().clear();
        objectCouponDaoConfig.getIdentityScope().clear();
        objectFaqDaoConfig.getIdentityScope().clear();
        objectFaqCommentDaoConfig.getIdentityScope().clear();
        objectFaqV2DaoConfig.getIdentityScope().clear();
    }

    public ObjectUserDao getObjectUserDao() {
        return objectUserDao;
    }

    public ObjectProductDao getObjectProductDao() {
        return objectProductDao;
    }

    public ObjectCategoryDao getObjectCategoryDao() {
        return objectCategoryDao;
    }

    public ObjectCountryDao getObjectCountryDao() {
        return objectCountryDao;
    }

    public ObjectCommentDao getObjectCommentDao() {
        return objectCommentDao;
    }

    public ObjectOptionDao getObjectOptionDao() {
        return objectOptionDao;
    }

    public ObjectProductOptionDao getObjectProductOptionDao() {
        return objectProductOptionDao;
    }

    public ObjectGroupProductDao getObjectGroupProductDao() {
        return objectGroupProductDao;
    }

    public ObjectGroupTimerDao getObjectGroupTimerDao() {
        return objectGroupTimerDao;
    }

    public ObjectCartDao getObjectCartDao() {
        return objectCartDao;
    }

    public ObjectOrderDeliveryDao getObjectOrderDeliveryDao() {
        return objectOrderDeliveryDao;
    }

    public ObjectBannerDao getObjectBannerDao() {
        return objectBannerDao;
    }

    public ObjectOrderHistoryDao getObjectOrderHistoryDao() {
        return objectOrderHistoryDao;
    }

    public ObjectCouponDao getObjectCouponDao() {
        return objectCouponDao;
    }

    public ObjectFaqDao getObjectFaqDao() {
        return objectFaqDao;
    }

    public ObjectFaqCommentDao getObjectFaqCommentDao() {
        return objectFaqCommentDao;
    }

    public ObjectFaqV2Dao getObjectFaqV2Dao() {
        return objectFaqV2Dao;
    }

}
