package antidote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_GROUP_TIMER.
 */
public class ObjectGroupTimer {

    private Long id;
    private Integer groupID;
    private Long productID;
    private Long time;

    public ObjectGroupTimer() {
    }

    public ObjectGroupTimer(Long id) {
        this.id = id;
    }

    public ObjectGroupTimer(Long id, Integer groupID, Long productID, Long time) {
        this.id = id;
        this.groupID = groupID;
        this.productID = productID;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getGroupID() {
        return groupID;
    }

    public void setGroupID(Integer groupID) {
        this.groupID = groupID;
    }

    public Long getProductID() {
        return productID;
    }

    public void setProductID(Long productID) {
        this.productID = productID;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
