package antidote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_ORDER_HISTORY.
 */
public class ObjectOrderHistory {

    private Long id;
    private Float total;
    private String createDate;

    public ObjectOrderHistory() {
    }

    public ObjectOrderHistory(Long id) {
        this.id = id;
    }

    public ObjectOrderHistory(Long id, Float total, String createDate) {
        this.id = id;
        this.total = total;
        this.createDate = createDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Float getTotal() {
        return total;
    }

    public void setTotal(Float total) {
        this.total = total;
    }

    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

}
