package antidote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_COMMENT.
 */
public class ObjectComment {

    private Long id;
    private Integer productID;
    private Integer userID;
    private String comment;
    private String createDate;
    private String firstName;
    private String lastName;
    private String image;
    private String idFacebook;

    public ObjectComment() {
    }

    public ObjectComment(Long id) {
        this.id = id;
    }

    public ObjectComment(Long id, Integer productID, Integer userID, String comment, String createDate, String firstName, String lastName, String image, String idFacebook) {
        this.id = id;
        this.productID = productID;
        this.userID = userID;
        this.comment = comment;
        this.createDate = createDate;
        this.firstName = firstName;
        this.lastName = lastName;
        this.image = image;
        this.idFacebook = idFacebook;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getProductID() {
        return productID;
    }

    public void setProductID(Integer productID) {
        this.productID = productID;
    }

    public Integer getUserID() {
        return userID;
    }

    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getIdFacebook() {
        return idFacebook;
    }

    public void setIdFacebook(String idFacebook) {
        this.idFacebook = idFacebook;
    }

}
