package antidote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_PRODUCT_OPTION.
 */
public class ObjectProductOption {

    private Long id;
    private Long productID;
    private Long optionID;
    private Integer option_index;
    private String value;
    private Float regularPrice;
    private Float salePrice;

    public ObjectProductOption() {
    }

    public ObjectProductOption(Long id) {
        this.id = id;
    }

    public ObjectProductOption(Long id, Long productID, Long optionID, Integer option_index, String value, Float regularPrice, Float salePrice) {
        this.id = id;
        this.productID = productID;
        this.optionID = optionID;
        this.option_index = option_index;
        this.value = value;
        this.regularPrice = regularPrice;
        this.salePrice = salePrice;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProductID() {
        return productID;
    }

    public void setProductID(Long productID) {
        this.productID = productID;
    }

    public Long getOptionID() {
        return optionID;
    }

    public void setOptionID(Long optionID) {
        this.optionID = optionID;
    }

    public Integer getOption_index() {
        return option_index;
    }

    public void setOption_index(Integer option_index) {
        this.option_index = option_index;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Float getRegularPrice() {
        return regularPrice;
    }

    public void setRegularPrice(Float regularPrice) {
        this.regularPrice = regularPrice;
    }

    public Float getSalePrice() {
        return salePrice;
    }

    public void setSalePrice(Float salePrice) {
        this.salePrice = salePrice;
    }

}
