package antidote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_PRODUCT.
 */
public class ObjectProduct {

    private Long id;
    private Long categoryID;
    private String name;
    private String slug;
    private String description;
    private Float regularPrice;
    private Float salePrice;
    private String priceRange;
    private String isActive;
    private String image;

    public ObjectProduct() {
    }

    public ObjectProduct(Long id) {
        this.id = id;
    }

    public ObjectProduct(Long id, Long categoryID, String name, String slug, String description, Float regularPrice, Float salePrice, String priceRange, String isActive, String image) {
        this.id = id;
        this.categoryID = categoryID;
        this.name = name;
        this.slug = slug;
        this.description = description;
        this.regularPrice = regularPrice;
        this.salePrice = salePrice;
        this.priceRange = priceRange;
        this.isActive = isActive;
        this.image = image;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCategoryID() {
        return categoryID;
    }

    public void setCategoryID(Long categoryID) {
        this.categoryID = categoryID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Float getRegularPrice() {
        return regularPrice;
    }

    public void setRegularPrice(Float regularPrice) {
        this.regularPrice = regularPrice;
    }

    public Float getSalePrice() {
        return salePrice;
    }

    public void setSalePrice(Float salePrice) {
        this.salePrice = salePrice;
    }

    public String getPriceRange() {
        return priceRange;
    }

    public void setPriceRange(String priceRange) {
        this.priceRange = priceRange;
    }

    public String getIsActive() {
        return isActive;
    }

    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

}
