package antidote;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import antidote.ObjectGroupTimer;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table OBJECT_GROUP_TIMER.
*/
public class ObjectGroupTimerDao extends AbstractDao<ObjectGroupTimer, Long> {

    public static final String TABLENAME = "OBJECT_GROUP_TIMER";

    /**
     * Properties of entity ObjectGroupTimer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property GroupID = new Property(1, Integer.class, "groupID", false, "GROUP_ID");
        public final static Property ProductID = new Property(2, Long.class, "productID", false, "PRODUCT_ID");
        public final static Property Time = new Property(3, Long.class, "time", false, "TIME");
    };


    public ObjectGroupTimerDao(DaoConfig config) {
        super(config);
    }
    
    public ObjectGroupTimerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'OBJECT_GROUP_TIMER' (" + //
                "'ID' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'GROUP_ID' INTEGER," + // 1: groupID
                "'PRODUCT_ID' INTEGER," + // 2: productID
                "'TIME' INTEGER);"); // 3: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'OBJECT_GROUP_TIMER'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ObjectGroupTimer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer groupID = entity.getGroupID();
        if (groupID != null) {
            stmt.bindLong(2, groupID);
        }
 
        Long productID = entity.getProductID();
        if (productID != null) {
            stmt.bindLong(3, productID);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(4, time);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ObjectGroupTimer readEntity(Cursor cursor, int offset) {
        ObjectGroupTimer entity = new ObjectGroupTimer( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // groupID
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // productID
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ObjectGroupTimer entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGroupID(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setProductID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setTime(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ObjectGroupTimer entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ObjectGroupTimer entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
