package antidote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_ORDER_DELIVERY.
 */
public class ObjectOrderDelivery {

    private Long id;
    private String orderDate;
    private String orderStatus;
    private String customerID;
    private String shippingFirstName;
    private String shippingLastName;
    private String shippingCompany;
    private String shippingAddress;
    private String shippingApartment;
    private String shippingCity;
    private String shippingCountry;
    private String shippingPostCode;
    private String shippingEmail;
    private String shippingPhone;
    private String shippingNote;
    private String subTotal;
    private String discount;
    private String shippingType;
    private String total;
    private String order_product;
    private String couponid;

    public ObjectOrderDelivery() {
    }

    public ObjectOrderDelivery(Long id) {
        this.id = id;
    }

    public ObjectOrderDelivery(Long id, String orderDate, String orderStatus, String customerID, String shippingFirstName, String shippingLastName, String shippingCompany, String shippingAddress, String shippingApartment, String shippingCity, String shippingCountry, String shippingPostCode, String shippingEmail, String shippingPhone, String shippingNote, String subTotal, String discount, String shippingType, String total, String order_product, String couponid) {
        this.id = id;
        this.orderDate = orderDate;
        this.orderStatus = orderStatus;
        this.customerID = customerID;
        this.shippingFirstName = shippingFirstName;
        this.shippingLastName = shippingLastName;
        this.shippingCompany = shippingCompany;
        this.shippingAddress = shippingAddress;
        this.shippingApartment = shippingApartment;
        this.shippingCity = shippingCity;
        this.shippingCountry = shippingCountry;
        this.shippingPostCode = shippingPostCode;
        this.shippingEmail = shippingEmail;
        this.shippingPhone = shippingPhone;
        this.shippingNote = shippingNote;
        this.subTotal = subTotal;
        this.discount = discount;
        this.shippingType = shippingType;
        this.total = total;
        this.order_product = order_product;
        this.couponid = couponid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }

    public String getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    public String getCustomerID() {
        return customerID;
    }

    public void setCustomerID(String customerID) {
        this.customerID = customerID;
    }

    public String getShippingFirstName() {
        return shippingFirstName;
    }

    public void setShippingFirstName(String shippingFirstName) {
        this.shippingFirstName = shippingFirstName;
    }

    public String getShippingLastName() {
        return shippingLastName;
    }

    public void setShippingLastName(String shippingLastName) {
        this.shippingLastName = shippingLastName;
    }

    public String getShippingCompany() {
        return shippingCompany;
    }

    public void setShippingCompany(String shippingCompany) {
        this.shippingCompany = shippingCompany;
    }

    public String getShippingAddress() {
        return shippingAddress;
    }

    public void setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress;
    }

    public String getShippingApartment() {
        return shippingApartment;
    }

    public void setShippingApartment(String shippingApartment) {
        this.shippingApartment = shippingApartment;
    }

    public String getShippingCity() {
        return shippingCity;
    }

    public void setShippingCity(String shippingCity) {
        this.shippingCity = shippingCity;
    }

    public String getShippingCountry() {
        return shippingCountry;
    }

    public void setShippingCountry(String shippingCountry) {
        this.shippingCountry = shippingCountry;
    }

    public String getShippingPostCode() {
        return shippingPostCode;
    }

    public void setShippingPostCode(String shippingPostCode) {
        this.shippingPostCode = shippingPostCode;
    }

    public String getShippingEmail() {
        return shippingEmail;
    }

    public void setShippingEmail(String shippingEmail) {
        this.shippingEmail = shippingEmail;
    }

    public String getShippingPhone() {
        return shippingPhone;
    }

    public void setShippingPhone(String shippingPhone) {
        this.shippingPhone = shippingPhone;
    }

    public String getShippingNote() {
        return shippingNote;
    }

    public void setShippingNote(String shippingNote) {
        this.shippingNote = shippingNote;
    }

    public String getSubTotal() {
        return subTotal;
    }

    public void setSubTotal(String subTotal) {
        this.subTotal = subTotal;
    }

    public String getDiscount() {
        return discount;
    }

    public void setDiscount(String discount) {
        this.discount = discount;
    }

    public String getShippingType() {
        return shippingType;
    }

    public void setShippingType(String shippingType) {
        this.shippingType = shippingType;
    }

    public String getTotal() {
        return total;
    }

    public void setTotal(String total) {
        this.total = total;
    }

    public String getOrder_product() {
        return order_product;
    }

    public void setOrder_product(String order_product) {
        this.order_product = order_product;
    }

    public String getCouponid() {
        return couponid;
    }

    public void setCouponid(String couponid) {
        this.couponid = couponid;
    }

}
