package antidote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_BANNER.
 */
public class ObjectBanner {

    private Long id;
    private String image;
    private String title;

    public ObjectBanner() {
    }

    public ObjectBanner(Long id) {
        this.id = id;
    }

    public ObjectBanner(Long id, String image, String title) {
        this.id = id;
        this.image = image;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
