package antidote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_COUNTRY.
 */
public class ObjectCountry {

    private Long id;
    private String code;
    private String slug;
    private String name;

    public ObjectCountry() {
    }

    public ObjectCountry(Long id) {
        this.id = id;
    }

    public ObjectCountry(Long id, String code, String slug, String name) {
        this.id = id;
        this.code = code;
        this.slug = slug;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
