package antidote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_FAQ_COMMENT.
 */
public class ObjectFaqComment {

    private Long id;
    private Long faqsID;
    private Long userID;
    private String comment;
    private String firstName;
    private String lastName;
    private String image;
    private String idFacebook;
    private String createDate;

    public ObjectFaqComment() {
    }

    public ObjectFaqComment(Long id) {
        this.id = id;
    }

    public ObjectFaqComment(Long id, Long faqsID, Long userID, String comment, String firstName, String lastName, String image, String idFacebook, String createDate) {
        this.id = id;
        this.faqsID = faqsID;
        this.userID = userID;
        this.comment = comment;
        this.firstName = firstName;
        this.lastName = lastName;
        this.image = image;
        this.idFacebook = idFacebook;
        this.createDate = createDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFaqsID() {
        return faqsID;
    }

    public void setFaqsID(Long faqsID) {
        this.faqsID = faqsID;
    }

    public Long getUserID() {
        return userID;
    }

    public void setUserID(Long userID) {
        this.userID = userID;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getIdFacebook() {
        return idFacebook;
    }

    public void setIdFacebook(String idFacebook) {
        this.idFacebook = idFacebook;
    }

    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

}
