package antidote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_CART.
 */
public class ObjectCart {

    private Long id;
    private Long productID;
    private String productName;
    private Integer quantity;
    private Float regularPrice;
    private Float salePrice;
    private Long idProductOption;
    private String nameProductOption;

    public ObjectCart() {
    }

    public ObjectCart(Long id) {
        this.id = id;
    }

    public ObjectCart(Long id, Long productID, String productName, Integer quantity, Float regularPrice, Float salePrice, Long idProductOption, String nameProductOption) {
        this.id = id;
        this.productID = productID;
        this.productName = productName;
        this.quantity = quantity;
        this.regularPrice = regularPrice;
        this.salePrice = salePrice;
        this.idProductOption = idProductOption;
        this.nameProductOption = nameProductOption;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProductID() {
        return productID;
    }

    public void setProductID(Long productID) {
        this.productID = productID;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Float getRegularPrice() {
        return regularPrice;
    }

    public void setRegularPrice(Float regularPrice) {
        this.regularPrice = regularPrice;
    }

    public Float getSalePrice() {
        return salePrice;
    }

    public void setSalePrice(Float salePrice) {
        this.salePrice = salePrice;
    }

    public Long getIdProductOption() {
        return idProductOption;
    }

    public void setIdProductOption(Long idProductOption) {
        this.idProductOption = idProductOption;
    }

    public String getNameProductOption() {
        return nameProductOption;
    }

    public void setNameProductOption(String nameProductOption) {
        this.nameProductOption = nameProductOption;
    }

}
