package antidote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_FAQ_V2.
 */
public class ObjectFaqV2 {

    private Long id;
    private String question;
    private String answer;
    private Integer sort;

    public ObjectFaqV2() {
    }

    public ObjectFaqV2(Long id) {
        this.id = id;
    }

    public ObjectFaqV2(Long id, String question, String answer, Integer sort) {
        this.id = id;
        this.question = question;
        this.answer = answer;
        this.sort = sort;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

}
