package antidote;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBJECT_GROUP_PRODUCT.
 */
public class ObjectGroupProduct {

    private Long id;
    private Integer groupID;
    private String name;
    private Long productID;
    private Integer timer;
    private String image;
    private Integer repeat_day;
    private String ingredient;
    private String description;

    public ObjectGroupProduct() {
    }

    public ObjectGroupProduct(Long id) {
        this.id = id;
    }

    public ObjectGroupProduct(Long id, Integer groupID, String name, Long productID, Integer timer, String image, Integer repeat_day, String ingredient, String description) {
        this.id = id;
        this.groupID = groupID;
        this.name = name;
        this.productID = productID;
        this.timer = timer;
        this.image = image;
        this.repeat_day = repeat_day;
        this.ingredient = ingredient;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getGroupID() {
        return groupID;
    }

    public void setGroupID(Integer groupID) {
        this.groupID = groupID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getProductID() {
        return productID;
    }

    public void setProductID(Long productID) {
        this.productID = productID;
    }

    public Integer getTimer() {
        return timer;
    }

    public void setTimer(Integer timer) {
        this.timer = timer;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Integer getRepeat_day() {
        return repeat_day;
    }

    public void setRepeat_day(Integer repeat_day) {
        this.repeat_day = repeat_day;
    }

    public String getIngredient() {
        return ingredient;
    }

    public void setIngredient(String ingredient) {
        this.ingredient = ingredient;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
