package antidote;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import antidote.ObjectProductOption;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table OBJECT_PRODUCT_OPTION.
*/
public class ObjectProductOptionDao extends AbstractDao<ObjectProductOption, Long> {

    public static final String TABLENAME = "OBJECT_PRODUCT_OPTION";

    /**
     * Properties of entity ObjectProductOption.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property ProductID = new Property(1, Long.class, "productID", false, "PRODUCT_ID");
        public final static Property OptionID = new Property(2, Long.class, "optionID", false, "OPTION_ID");
        public final static Property Option_index = new Property(3, Integer.class, "option_index", false, "OPTION_INDEX");
        public final static Property Value = new Property(4, String.class, "value", false, "VALUE");
        public final static Property RegularPrice = new Property(5, Float.class, "regularPrice", false, "REGULAR_PRICE");
        public final static Property SalePrice = new Property(6, Float.class, "salePrice", false, "SALE_PRICE");
    };


    public ObjectProductOptionDao(DaoConfig config) {
        super(config);
    }
    
    public ObjectProductOptionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'OBJECT_PRODUCT_OPTION' (" + //
                "'ID' INTEGER PRIMARY KEY ," + // 0: id
                "'PRODUCT_ID' INTEGER," + // 1: productID
                "'OPTION_ID' INTEGER," + // 2: optionID
                "'OPTION_INDEX' INTEGER," + // 3: option_index
                "'VALUE' TEXT," + // 4: value
                "'REGULAR_PRICE' REAL," + // 5: regularPrice
                "'SALE_PRICE' REAL);"); // 6: salePrice
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'OBJECT_PRODUCT_OPTION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ObjectProductOption entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long productID = entity.getProductID();
        if (productID != null) {
            stmt.bindLong(2, productID);
        }
 
        Long optionID = entity.getOptionID();
        if (optionID != null) {
            stmt.bindLong(3, optionID);
        }
 
        Integer option_index = entity.getOption_index();
        if (option_index != null) {
            stmt.bindLong(4, option_index);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(5, value);
        }
 
        Float regularPrice = entity.getRegularPrice();
        if (regularPrice != null) {
            stmt.bindDouble(6, regularPrice);
        }
 
        Float salePrice = entity.getSalePrice();
        if (salePrice != null) {
            stmt.bindDouble(7, salePrice);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ObjectProductOption readEntity(Cursor cursor, int offset) {
        ObjectProductOption entity = new ObjectProductOption( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // productID
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // optionID
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // option_index
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // value
            cursor.isNull(offset + 5) ? null : cursor.getFloat(offset + 5), // regularPrice
            cursor.isNull(offset + 6) ? null : cursor.getFloat(offset + 6) // salePrice
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ObjectProductOption entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setProductID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setOptionID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setOption_index(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setValue(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRegularPrice(cursor.isNull(offset + 5) ? null : cursor.getFloat(offset + 5));
        entity.setSalePrice(cursor.isNull(offset + 6) ? null : cursor.getFloat(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ObjectProductOption entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ObjectProductOption entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
